-- GOOGLE-LOGIN ONLINE BIDDING SECURITY PATCH
-- Run this AFTER supabase.sql in Supabase SQL Editor.

-- Store the authenticated Google user on online bids.
alter table public.bids add column if not exists auth_user_id uuid;
alter table public.bids add column if not exists bidder_email text;

-- Online bidders must be authenticated. Admin/offline actions also remain authenticated.
create or replace function public.place_bid(
  p_item_number integer,
  p_bidder_name text,
  p_amount numeric,
  p_source text default 'online'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  a auction_state%rowtype;
  v_user_id uuid := auth.uid();
  v_email text := auth.jwt() ->> 'email';
  v_name text := trim(coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name', p_bidder_name, v_email, 'Google user'));
begin
  if v_user_id is null then
    return jsonb_build_object('ok', false, 'message', 'Please sign in with Google before bidding.');
  end if;

  if p_source not in ('online','offline') then
    return jsonb_build_object('ok', false, 'message', 'Invalid bid source.');
  end if;

  select * into a from public.auction_state where id = 1 for update;

  if a.status <> 'open' then
    return jsonb_build_object('ok', false, 'message', 'Bidding is closed.');
  end if;

  if p_item_number <> a.item_number then
    return jsonb_build_object('ok', false, 'message', 'This item is no longer active.');
  end if;

  if length(v_name) < 2 then
    return jsonb_build_object('ok', false, 'message', 'Could not determine your name.');
  end if;

  if p_amount <= a.current_bid then
    return jsonb_build_object('ok', false, 'message', 'Your bid must be higher than ₹' || to_char(a.current_bid, 'FM9999999990.00'));
  end if;

  update public.auction_state
  set current_bid = p_amount,
      highest_bidder = v_name,
      highest_bid_source = p_source,
      updated_at = now()
  where id = 1;

  insert into public.bids(item_number, bidder_name, amount, source, auth_user_id, bidder_email)
  values (p_item_number, v_name, p_amount, p_source, v_user_id, v_email);

  return jsonb_build_object('ok', true, 'message', 'Bid accepted.');
end;
$$;

-- Only signed-in users can call the bidding RPC.
revoke execute on function public.place_bid(integer,text,numeric,text) from public;
revoke execute on function public.place_bid(integer,text,numeric,text) from anon;
grant execute on function public.place_bid(integer,text,numeric,text) to authenticated;


-- Admin action: clear all bidding history (requires a signed-in user).
create or replace function public.clear_bidding_history()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return jsonb_build_object('ok', false, 'message', 'Admin login required.');
  end if;
  delete from public.bids;
  return jsonb_build_object('ok', true, 'message', 'Bidding history cleared.');
end;
$$;

revoke execute on function public.clear_bidding_history() from public;
grant execute on function public.clear_bidding_history() to authenticated;

-- BIDDER AGE / ADDRESS + UNDER-18 ATTEMPT LOG
alter table public.bids add column if not exists bidder_address text;
alter table public.bids add column if not exists bidder_age integer;

create table if not exists public.underage_bidding_attempts (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  age integer not null,
  attempted_at timestamptz not null default now()
);

alter table public.underage_bidding_attempts enable row level security;
drop policy if exists "authenticated delete underage attempts" on public.underage_bidding_attempts;
create policy "authenticated delete underage attempts" on public.underage_bidding_attempts for delete to authenticated using (true);
drop policy if exists "authenticated read underage attempts" on public.underage_bidding_attempts;
create policy "authenticated read underage attempts" on public.underage_bidding_attempts
for select to authenticated using (true);

drop function if exists public.log_underage_bidding_attempt(text,text,integer);
create or replace function public.log_underage_bidding_attempt(p_name text,p_address text,p_age integer)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.underage_bidding_attempts(name,address,age) values (trim(p_name),trim(p_address),p_age);
  return jsonb_build_object('ok',true);
end;
$$;
revoke execute on function public.log_underage_bidding_attempt(text,text,integer) from public;
grant execute on function public.log_underage_bidding_attempt(text,text,integer) to anon, authenticated;

-- Resolve overloaded place_bid functions before creating the age/address version.
drop function if exists public.place_bid(integer,text,numeric,text);
drop function if exists public.place_bid(integer,text,numeric,text,integer,text);


drop function if exists public.place_bid(integer,text,numeric,text);
create or replace function public.place_bid(
  p_item_number integer,
  p_bidder_name text,
  p_amount numeric,
  p_source text,
  p_bidder_age integer,
  p_bidder_address text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  a auction_state%rowtype;
  v_user_id uuid := auth.uid();
  v_email text := auth.jwt() ->> 'email';
  v_name text := trim(split_part(coalesce(p_bidder_name,''),'|||',1));
  v_address text := trim(coalesce(p_bidder_address, split_part(coalesce(p_bidder_name,''),'|||',3), ''));
begin
  if v_user_id is null then
    return jsonb_build_object('ok', false, 'message', 'Please sign in with Google before bidding.');
  end if;
  if p_source not in ('online','offline') then
    return jsonb_build_object('ok', false, 'message', 'Invalid bid source.');
  end if;
  if p_source='online' and (p_bidder_age is null or p_bidder_age < 18) then
    return jsonb_build_object('ok', false, 'message', 'Bidding is restricted to users aged 18 or above.');
  end if;
  select * into a from public.auction_state where id = 1 for update;
  if a.status <> 'open' then return jsonb_build_object('ok', false, 'message', 'Bidding is closed.'); end if;
  if p_item_number <> a.item_number then return jsonb_build_object('ok', false, 'message', 'This item is no longer active.'); end if;
  if length(v_name) < 2 then return jsonb_build_object('ok', false, 'message', 'Could not determine your name.'); end if;
  if p_source='online' and length(v_address) < 5 then return jsonb_build_object('ok', false, 'message', 'Please provide your address.'); end if;
  if p_amount <= a.current_bid then return jsonb_build_object('ok', false, 'message', 'Your bid must be higher than ₹' || to_char(a.current_bid, 'FM9999999990.00')); end if;

  update public.auction_state
  set current_bid=p_amount,
      highest_bidder=v_name || '|||' || coalesce(v_email,'') || '|||' || v_address,
      highest_bid_source=p_source,
      updated_at=now()
  where id=1;

  insert into public.bids(item_number,bidder_name,amount,source,auth_user_id,bidder_email,bidder_address,bidder_age)
  values(p_item_number,v_name,p_amount,p_source,v_user_id,v_email,v_address,p_bidder_age);
  return jsonb_build_object('ok',true,'message','Bid accepted.');
end;
$$;
revoke execute on function public.place_bid(integer,text,numeric,text,integer,text) from public;
revoke execute on function public.place_bid(integer,text,numeric,text,integer,text) from anon;
grant execute on function public.place_bid(integer,text,numeric,text,integer,text) to authenticated;


-- Admin cleanup for under-18 attempt notifications.
drop function if exists public.delete_underage_bidding_attempt(bigint);
create or replace function public.delete_underage_bidding_attempt(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'message','Admin login required.'); end if;
  delete from public.underage_bidding_attempts where id=p_id;
  return jsonb_build_object('ok',true,'message','Under-18 attempt deleted.');
end;
$$;
revoke execute on function public.delete_underage_bidding_attempt(bigint) from public, anon;
grant execute on function public.delete_underage_bidding_attempt(bigint) to authenticated;

drop function if exists public.delete_all_underage_bidding_attempts();
create or replace function public.delete_all_underage_bidding_attempts()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'message','Admin login required.'); end if;
  delete from public.underage_bidding_attempts;
  return jsonb_build_object('ok',true,'message','All under-18 attempts deleted.');
end;
$$;
revoke execute on function public.delete_all_underage_bidding_attempts() from public, anon;
grant execute on function public.delete_all_underage_bidding_attempts() to authenticated;
