
-- CHURCH AUCTION DATABASE
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.auction_state (
  id bigint primary key default 1,
  church_name text not null default 'Church Harvest Festival Auction',
  item_name text not null default 'Waiting for next item',
  starting_bid numeric(12,2) not null default 0,
  current_bid numeric(12,2) not null default 0,
  highest_bidder text,
  highest_bid_source text,
  status text not null default 'waiting' check (status in ('waiting','open','sold')),
  item_number integer not null default 1,
  updated_at timestamptz not null default now()
);

insert into public.auction_state (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.bids (
  id bigint generated by default as identity primary key,
  item_number integer not null,
  bidder_name text not null,
  amount numeric(12,2) not null,
  source text not null check (source in ('online','offline')),
  created_at timestamptz not null default now()
);

alter table public.auction_state enable row level security;
alter table public.bids enable row level security;

-- Public visitors can read the current auction and bid history.
drop policy if exists "public read auction state" on public.auction_state;
create policy "public read auction state"
on public.auction_state for select to anon, authenticated using (true);

drop policy if exists "public read bids" on public.bids;
create policy "public read bids"
on public.bids for select to anon, authenticated using (true);

-- Only authenticated users may directly modify the auction state.
drop policy if exists "authenticated update auction state" on public.auction_state;
create policy "authenticated update auction state"
on public.auction_state for update to authenticated using (true) with check (true);

-- Bidders use the safe RPC below instead of inserting bids directly.
revoke insert, update, delete on public.bids from anon, authenticated;

create or replace function public.place_bid(
  p_item_number integer,
  p_bidder_name text,
  p_amount numeric,
  p_source text default 'online'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  a auction_state%rowtype;
begin
  select * into a from public.auction_state where id = 1 for update;

  if a.status <> 'open' then
    return jsonb_build_object('ok', false, 'message', 'Bidding is closed.');
  end if;

  if p_item_number <> a.item_number then
    return jsonb_build_object('ok', false, 'message', 'This item is no longer active.');
  end if;

  if length(trim(p_bidder_name)) < 2 then
    return jsonb_build_object('ok', false, 'message', 'Enter your name.');
  end if;

  if p_amount <= a.current_bid then
    return jsonb_build_object('ok', false, 'message',
      'Your bid must be higher than ₹' || to_char(a.current_bid, 'FM9999999990.00'));
  end if;

  if p_source not in ('online','offline') then
    return jsonb_build_object('ok', false, 'message', 'Invalid bid source.');
  end if;

  update public.auction_state
  set current_bid = p_amount,
      highest_bidder = trim(p_bidder_name),
      highest_bid_source = p_source,
      updated_at = now()
  where id = 1;

  insert into public.bids(item_number, bidder_name, amount, source)
  values (p_item_number, trim(p_bidder_name), p_amount, p_source);

  return jsonb_build_object('ok', true, 'message', 'Bid accepted.');
end;
$$;

grant execute on function public.place_bid(integer,text,numeric,text) to anon, authenticated;

-- Enable Realtime for both tables.
do $$
begin
  alter publication supabase_realtime add table public.auction_state;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.bids;
exception when duplicate_object then null;
end $$;


-- Admin action: clear all bidding history (requires a signed-in user).
create or replace function public.clear_bidding_history()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return jsonb_build_object('ok', false, 'message', 'Admin login required.');
  end if;
  delete from public.bids;
  return jsonb_build_object('ok', true, 'message', 'Bidding history cleared.');
end;
$$;

revoke execute on function public.clear_bidding_history() from public;
grant execute on function public.clear_bidding_history() to authenticated;
